apiVersion: apps/v1
kind: Deployment
metadata:
  name: depviz-ui
  labels:
    app: depviz-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depviz-ui
  template:
    metadata:
      labels:
        app: depviz-ui
    spec:
      containers:
      - name: depviz-ui
        image: depviz-ui:dev
        env:
        - name: BACKEND_HOST
          value: "depviz-server"
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: depviz-ui
spec:
  selector:
    app: depviz-ui
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: LoadBalancer
