apiVersion: apps/v1
kind: Deployment
metadata:
  name: depviz-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depviz-server
  template:
    metadata:
      labels:
        app: depviz-server
    spec:
      containers:
        - name: depviz-server
          image: depviz-server:dev
#          imagePullPolicy: IfNotPresent
          # For local development
          imagePullPolicy: Never
          ports:
            - name: otlp-grpc
              containerPort: 4317
---
apiVersion: v1
kind: Service
metadata:
  name: depviz-server
spec:
  selector:
    app: depviz-server
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
  type: ClusterIP
